name: Bug Report
description: Report bugs or issues.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you.

  - type: checkboxes
    attributes:
      label: Check existing issues
      description: By submitting this issue, you checked there isn't already an issue for this bug.
      options:
        - label: I checked there isn't already an issue for the bug I encountered.
          required: true

  - type: input
    attributes:
      label: poly-bench Version
      description: What version of poly-bench are you using? (run `poly-bench --version`)
      placeholder: x.y.z (do not write `latest`)
    validations:
      required: true

  - type: input
    attributes:
      label: Command / Workflow
      description: What command were you running when the issue occurred?
      placeholder: poly-bench run examples/hash.bench --lang go
    validations:
      required: true

  - type: input
    attributes:
      label: Environment
      description: OS and toolchain versions (Rust, Node.js, Go if relevant)
      placeholder: macOS 15.0, rustc 1.xx, node 20.x, go1.22.x
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps, sample `.bench` file, or command sequence to reproduce the behavior.
      placeholder: |
        1. Run `poly-bench init demo`
        2. Add benchmark file ...
        3. Run `poly-bench run ...`
        4. Observe error ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproduction
      description: Please provide the smallest reproducible example (benchmark file, command, or snippet).
      render: text
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error Output
      description: If applicable, paste the full error message or stack trace.
      render: shell
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any other context about the problem? OS, environment details, related issues?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
