// Code generated by poly-bench. Do not edit.
// This file ensures go.sum includes all required dependencies.

package main

import (
	_ "github.com/ethereum/go-ethereum"
	_ "golang.org/x/crypto/sha3"
	_ "github.com/ChefBingbong/viem-go"
)

func main() {}
